name: Continous Intergration

on:
    push:
        branches: [ hotfix/*, dev ]
    pull_request:
        branches: [ dev, main ]
    workflow_call:

permissions:
    contents: read

jobs:
    test_build_api:
        name: Test & Build API
        runs-on: windows-latest
        defaults:
            run:
              working-directory: ./api
        
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v3

          - name: Setup JDK 17 and Cache
            uses: actions/setup-java@v3
            with:
                java-version: '17'
                distribution: 'temurin'

          - name: Test API
            run: ./gradlew.bat test
            
          - name: Build API
            run: ./gradlew.bat build

    test_build_app:
      name: Test & Build App
      runs-on: ubuntu-latest
      defaults:
          run:
            working-directory: ./app/HealthQuest
      
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v3
        
        - name: Setup NodeJS and Cache
          uses: actions/setup-node@v3
          with:
            node-version: 16
            cache: 'npm'

        - name: Test App
          run: npm run test
          
        - name: Build App
          run: npm run build